version: "3.7"

services:

  postgres:
    image: postgres:11-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${MOODLE_DB_NAME}
      - POSTGRES_USER=${MOODLE_DB_USER}
      - POSTGRES_PASSWORD=${MOODLE_DB_PASSWORD}
    networks:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - 7070:7070
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - www:/var/www/html/postgresql
      - moodledata:/var/moodledata/postgres
    networks:
      - backend
    depends_on:
      - moodle

# add image:
  moodle:
    build:
      context: ./moodle
      dockerfile: Dockerfile
    volumes:
      - www:/var/www/html
      - moodledata:/var/moodledata
    networks:
      - backend
    env_file: .env

volumes:
  postgres:
  www:
  moodledata:

networks:
  backend: